export const memesInfo = [
	{ name: '1.jpg', category: 'ayf', title: 'Сходи к врачу', humor: 8, relatability: 9, impact: 10 },
	{ name: '2.jpg', category: 'ayf', title: 'Знак Вселенной', humor: 7, relatability: 7, impact: 10 },
	{ name: '3.jpg', category: 'ayf', title: 'Аминь', humor: 0, relatability: 1, impact: 1 },
	{ name: '4.jpg', category: 'ayf', title: 'Мужчины ух', humor: 7, relatability: 6, impact: 6 },
	{ name: '5.jpg', category: 'ayf', title: 'Gо дружбе', humor: 3, relatability: 1, impact: 9 },
	{ name: '6.jpg', category: 'ayf', title: 'Мнения?', humor: 2, relatability: 1, impact: 3 },
	{ name: '7.jpg', category: 'ayf', title: 'Собачий вальс', humor: 9, relatability: 8, impact: 1 },
	{ name: '8.jpg', category: 'ayf', title: 'Ты попробуй', humor: 10, relatability: 1, impact: 6 },
	{ name: '1.jpg', category: 'chat', title: 'Мама знает', humor: 3, relatability: 10, impact: 7 },
	{ name: '2.jpg', category: 'chat', title: 'Ладно', humor: 4, relatability: 7, impact: 10 },
	{ name: '3.jpg', category: 'chat', title: 'Βαβυλών', humor: 7, relatability: 9, impact: 0 },
	{ name: '4.jpg', category: 'chat', title: 'Намек', humor: 3, relatability: 10, impact: 0 },
	{ name: '5.jpg', category: 'chat', title: 'Повезло', humor: 8, relatability: 1, impact: 7 },
	{ name: '6.jpg', category: 'chat', title: 'Где?', humor: 6, relatability: 8, impact: 4 },
	{ name: '7.jpg', category: 'chat', title: 'Нет', humor: 10, relatability: 9, impact: 4 },
	{ name: '8.jpg', category: 'chat', title: '🤝', humor: 6, relatability: 7, impact: 6 },
	{ name: '9.jpg', category: 'chat', title: 'Пожалуйста', humor: 4, relatability: 5, impact: 1 },
	{ name: '1.jpg', category: 'lotsoftext', title: 'Факт', humor: 2, relatability: 8, impact: 2 },
	{ name: '2.jpg', category: 'lotsoftext', title: 'Чит', humor: 9, relatability: 10, impact: 2 },
	{ name: '3.jpg', category: 'lotsoftext', title: 'Минусы?', humor: 0, relatability: 9, impact: 8 },
	{ name: '4.jpg', category: 'lotsoftext', title: 'В студию.', humor: 6, relatability: 0, impact: 10 },
	{ name: '5.jpg', category: 'lotsoftext', title: 'Дома', humor: 2, relatability: 1, impact: 5 },
	{ name: '6.jpg', category: 'lotsoftext', title: 'Стоит', humor: 5, relatability: 3, impact: 7 },
	{ name: '7.jpg', category: 'lotsoftext', title: 'Стоило бы', humor: 8, relatability: 10, impact: 10 },
	{ name: '8.jpg', category: 'lotsoftext', title: 'МОЙ', humor: 4, relatability: 6, impact: 8 },
	{ name: '1.jpg', category: 'mood', title: 'Отличия есть', humor: 2, relatability: 3, impact: 4 },
	{ name: '2.jpg', category: 'mood', title: 'И у меня', humor: 1, relatability: 1, impact: 8 },
	{ name: '3.jpg', category: 'mood', title: 'Кормить сюда', humor: 6, relatability: 7, impact: 1 },
	{ name: '4.jpg', category: 'mood', title: 'Муся-Муся...', humor: 0, relatability: 10, impact: 9 },
	{ name: '5.jpg', category: 'mood', title: 'Обидно', humor: 1, relatability: 4, impact: 3 },
	{ name: '6.jpg', category: 'mood', title: 'Эх', humor: 5, relatability: 5, impact: 9 },
	{ name: '7.jpg', category: 'mood', title: 'Мудро', humor: 9, relatability: 0, impact: 5 },
	{ name: '8.jpg', category: 'mood', title: 'Быдло', humor: 10, relatability: 6, impact: 9 },
	{ name: '9.jpg', category: 'mood', title: 'Хотеть', humor: 7, relatability: 9, impact: 7 },
	{ name: '1.jpg', category: 'other', title: '1666', humor: 2, relatability: 3, impact: 4 },
	{ name: '2.jpg', category: 'other', title: 'Зачем', humor: 9, relatability: 9, impact: 3 },
	{ name: '3.jpg', category: 'other', title: 'Ох уж да', humor: 2, relatability: 6, impact: 2 },
	{ name: '4.jpg', category: 'other', title: 'Кошочьки', humor: 4, relatability: 2, impact: 1 },
	{ name: '5.jpg', category: 'other', title: 'Я видела', humor: 9, relatability: 0, impact: 10 },
	{ name: '6.jpg', category: 'other', title: 'Все хорошо', humor: 9, relatability: 2, impact: 5 },
	{ name: '7.jpg', category: 'other', title: 'Стыдно', humor: 10, relatability: 6, impact: 6 },
	{ name: '8.jpg', category: 'other', title: 'Спасибо', humor: 6, relatability: 8, impact: 6 },
	{ name: '9.jpg', category: 'other', title: 'Давно пора', humor: 7, relatability: 7, impact: 6 },
	{ name: '10.jpg', category: 'other', title: 'Не промахиваясь', humor: 9, relatability: 7, impact: 5 },
]